package employeedatabase;

import static employeedatabase.GUI.fullTable;
import static employeedatabase.GUI.jTabbedPane1;
import static employeedatabase.GUI.searchTable;

public class EditEmployee extends javax.swing.JFrame {

    private static EmployeeData editedObject;
    private static FullTimeEmployee fullTime;
    private static PartTimeEmployee partTime;
    
    public EditEmployee(EmployeeData arg) {
        super("Edit Employee " + arg.getEmpNumber()); 
        initComponents();
        editedObject = arg;
        setFormsActiveOrInactive(arg);
        setDefaultCloseOperation(EditEmployee.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        firstNameLabel = new javax.swing.JLabel();
        firstNameForm = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameForm = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        locationForm = new javax.swing.JTextField();
        deductionRateLabel = new javax.swing.JLabel();
        deductionRateForm = new javax.swing.JTextField();
        annualSalaryLabel = new javax.swing.JLabel();
        annualSalaryForm = new javax.swing.JTextField();
        hourlyWageLabel = new javax.swing.JLabel();
        hourlyWageForm = new javax.swing.JTextField();
        hoursPerWeekLabel = new javax.swing.JLabel();
        hoursPerWeekForm = new javax.swing.JTextField();
        weeksPerYearLabel = new javax.swing.JLabel();
        weeksPerYearForm = new javax.swing.JTextField();
        employeeNumberForm = new javax.swing.JTextField();
        deductionRateLabel1 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNameLabel.setText("Last Name");

        firstNameForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFormActionPerformed(evt);
            }
        });

        lastNameLabel.setText("First Name");

        lastNameForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFormActionPerformed(evt);
            }
        });

        locationLabel.setText("Location");

        deductionRateLabel.setText("Deduction Rate");

        annualSalaryLabel.setText("Annual Salary");

        hourlyWageLabel.setText("Hourly Wage");

        hoursPerWeekLabel.setText("Hours per Week");

        weeksPerYearLabel.setText("Weeks per Year");

        deductionRateLabel1.setText("Employee Number");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameLabel)
                                    .addComponent(firstNameLabel)
                                    .addComponent(deductionRateLabel)
                                    .addComponent(locationLabel)
                                    .addComponent(deductionRateLabel1))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(locationForm)
                                    .addComponent(lastNameForm)
                                    .addComponent(firstNameForm)
                                    .addComponent(deductionRateForm, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(employeeNumberForm, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(annualSalaryLabel)
                                    .addComponent(hourlyWageLabel)
                                    .addComponent(hoursPerWeekLabel)
                                    .addComponent(weeksPerYearLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hoursPerWeekForm, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hourlyWageForm, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(annualSalaryForm)
                                    .addComponent(weeksPerYearForm, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deductionRateLabel)
                    .addComponent(deductionRateForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deductionRateLabel1)
                    .addComponent(employeeNumberForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annualSalaryLabel)
                    .addComponent(annualSalaryForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourlyWageLabel)
                    .addComponent(hourlyWageForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursPerWeekLabel)
                    .addComponent(hoursPerWeekForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weeksPerYearLabel)
                    .addComponent(weeksPerYearForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        firstNameForm.getAccessibleContext().setAccessibleName("");
        lastNameForm.getAccessibleContext().setAccessibleName("");
        locationForm.getAccessibleContext().setAccessibleName("");
        deductionRateForm.getAccessibleContext().setAccessibleName("");
        employeeNumberForm.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFormActionPerformed

    private void lastNameFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFormActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if (editedObject.getFullTime()) {
            fullTime.setFirstName(firstNameForm.getText());
            fullTime.setLastName(lastNameForm.getText());
            fullTime.setLocation(locationForm.getText());
            fullTime.setDeduction(Double.parseDouble(deductionRateForm.getText()));
            fullTime.setSalary(Double.parseDouble(annualSalaryForm.getText()));
            if (GUI.jTabbedPane1.getSelectedIndex() == 1) {
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) GUI.searchTable.getModel();
                model.setRowCount(0);
                Object[] row = {fullTime.getFirstName(), 
                            fullTime.getLastName(), 
                            fullTime.getLocation(), 
                            fullTime.getEmpNumber(), 
                            true, 
                            fullTime.getSalary(), 
                            fullTime.getDeduction(),
                            null,
                            null,
                            null};
                model.addRow(row);
            } else if (GUI.jTabbedPane1.getSelectedIndex() == 0) {
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) searchTable.getModel();
                model.setRowCount(0);
                model = (javax.swing.table.DefaultTableModel) fullTable.getModel();
                model.setRowCount(0);
                Primary.bigList.hashToTable();
                jTabbedPane1.setSelectedIndex(0);
            }
        } else if (!editedObject.getFullTime()) {
            partTime.setFirstName(firstNameForm.getText());
            partTime.setLastName(lastNameForm.getText());
            partTime.setLocation(locationForm.getText());
            partTime.setDeduction(Double.parseDouble(deductionRateForm.getText()));
            partTime.setHourlyWage(Double.parseDouble(hourlyWageForm.getText()));
            partTime.setWeeks(Integer.parseInt(hoursPerWeekForm.getText()));
            partTime.setSalary(Double.parseDouble(weeksPerYearForm.getText()));
            if (GUI.jTabbedPane1.getSelectedIndex() == 1) {
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) GUI.searchTable.getModel();
                model.setRowCount(0);
                Object[] row = {partTime.getFirstName(), 
                            partTime.getLastName(), 
                            partTime.getLocation(), 
                            partTime.getEmpNumber(), 
                            false, 
                            (partTime.getHourlyWage()*partTime.getPerYear()*partTime.getWeeks()), 
                            partTime.getDeduction(),
                            partTime.getHourlyWage(),
                            partTime.getWeeks(),
                            partTime.getPerYear()};
                model.addRow(row);
            } else if (GUI.jTabbedPane1.getSelectedIndex() == 0) {
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) searchTable.getModel();
                model.setRowCount(0);
                model = (javax.swing.table.DefaultTableModel) fullTable.getModel();
                model.setRowCount(0);
                Primary.bigList.hashToTable();
                jTabbedPane1.setSelectedIndex(0);
            }  
        } 
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    
    private void setFormsActiveOrInactive(EmployeeData arg) {
        lastNameForm.setText(arg.getLastName());
        firstNameForm.setText(arg.getFirstName());
        locationForm.setText(arg.getLocation());
        deductionRateForm.setText(Double.toString(arg.getDeduction()));
        employeeNumberForm.setText(Integer.toString(arg.getEmpNumber()));
        employeeNumberForm.setEnabled(false);
        if (arg.getFullTime()) {
            hourlyWageForm.setEnabled(false);
            hoursPerWeekForm.setEnabled(false);
            weeksPerYearForm.setEnabled(false);
            fullTime = (FullTimeEmployee) arg;
            annualSalaryForm.setText(Double.toString(fullTime.getSalary()));
        } else if (!arg.getFullTime()) {
            annualSalaryForm.setEnabled(false);
            partTime = (PartTimeEmployee) arg;
            hourlyWageForm.setText(Double.toString(partTime.getHourlyWage()));
            hoursPerWeekForm.setText(Double.toString(partTime.getWeeks()));
            weeksPerYearForm.setText(Double.toString(partTime.getPerYear()));
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee(editedObject).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annualSalaryForm;
    private javax.swing.JLabel annualSalaryLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField deductionRateForm;
    private javax.swing.JLabel deductionRateLabel;
    private javax.swing.JLabel deductionRateLabel1;
    private javax.swing.JTextField employeeNumberForm;
    private javax.swing.JTextField firstNameForm;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField hourlyWageForm;
    private javax.swing.JLabel hourlyWageLabel;
    private javax.swing.JTextField hoursPerWeekForm;
    private javax.swing.JLabel hoursPerWeekLabel;
    private javax.swing.JTextField lastNameForm;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField locationForm;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField weeksPerYearForm;
    private javax.swing.JLabel weeksPerYearLabel;
    // End of variables declaration//GEN-END:variables
}
